### ISSUE TITLE
SHARDNET: improve reliability of validator-to-validator communication

### ISSUE THREAD

**Issue by paulmattei** [kuutamolabs/near-staking-knd#144]
We have added a network.public_addrs field to the config.json, which will allow us to improve reliability of validator-to-validator communication (design - https://docs.google.com/document/d/1RDd9ETfLQL_JfnEePmUPjkLvIxAtLV-c5AKWV8IMJEo/edit#heading=h.x8zofr2t0ji1).

Please update your config.json file as described below and restart the node.
1. Determine your node’s public IP. You can do it for example by running the following command on the machine on which you run your node.
curl ifconfig.me
2. Determine your node’s public key. You can find it in the node_key.json file (copy the whole value of the public key, including the “ed25519:” prefix):
{
    “Account_id”: “node”,
    “public_key”: “ed25519:examplepublickeyexamplepublickey”
    “secret_key”: …
}
3. To your config.json add “public_addrs” line, as follows (if network.addr in your config specifies a different port than 24567, copy it over to the public_addrs field):
{
    “genesis_file”: …
    …
            “network”: {
        “addr”: “0.0.0.0:24567”,
        “boot_nodes”: …,
        “public_addrs”: [“<public key>@<public IP>:24567”],
        …
    }
    …
}

Example value of public_addrs (your value should follow the same format): ["ed25519:86EtEy7epneKyrcJwSWP7zsisTkfDRH5CFVszt4qiQYw@31.192.22.209:24567"]

4. Restart your node, because changes to the config are only noticed by the node upon a restart.

**Comment by Mic92** [comment]
I can add a nixos option to make this setting configurable in the configuration.nix but I cannot magically figure out this value for all of our users. So some manual intervention is required.

**Comment by Mic92** [comment]
implemented in https://github.com/kuutamolabs/near-staking-knd/commit/e248e47d7764b07e6045e120e4a1423ba7325c3b
