### ISSUE TITLE
Can we create a github actions job to regularly update backup URL value?

### ISSUE THREAD

**Issue by paulmattei** [kuutamolabs/near-staking-knd#338]
that is set at kuutamo.neard.s3.dataBackupDirectory

**Comment by Mic92** [comment]
I will use this trick for the single node validator: https://github.com/kuutamolabs/near-staking-knd/blob/aefa6e9937372ccb2614818e27e288eb8782e3ed/nix/modules/single-node-validator/mainnet.nix#L7
